In [311]:
import numpy as np

In [312]:
A = np.array([
    [2,8,2,14],
    [1,6,-1,13],
    [2,-1,2,5]
])
A_copy = np.array([
    [2,8,2,14],
    [1,6,-1,13],
    [2,-1,2,5]
])

In [313]:
def upper_triangular_1(B):
    A = B.copy()
    rows = len(A)
    columns = len(A[0])
    if ( rows != (columns-1)):
        print('not square matrix')
        return None
    for j in range(columns-1):
        for i in range(j+1,rows):
            factor = A[i,j] / A[j,j]
            for k in range(j,columns):
                A[i,k] = A[i,k] - factor * A[j,k] 
    return A
              

def upper_triangular_2(A):
    B = A.copy()
    rows = len(B)
    columns = len(B[0])
    if ( rows != (columns-1)):
        print('not square matrix')
        return None
    for j in range(columns-1):
        for i in range (j+1,rows):
            B[i] = B[i] - (B[i,j]/B[j,j]) * B[j]
    return B


In [314]:
def gauss_solver1(B):
    A = upper_triangular_1(B)
    a = A[:,:-1]
    b = A[:,-1]
    
    roots = np.zeros(len(b))
    
    for i in range(rows-1,-1,-1): 
        if(i == (rows -1)):
            roots[i] = (b[i]) / a[i,i]
        else:
            summ = int(sum(roots * a[i]))
            roots[i] = (b[i] - summ) / a[i,i]
            summ=0
    print('Matrix:')
    print(A)
    print('\nRoots:')
    print(roots)

In [315]:
def gauss_solver2(B):
    A = upper_triangular_2(B)
    a = A[:,:-1]
    b = A[:,-1]
    
    roots = np.zeros(len(b))
    
    for i in range(rows-1,-1,-1): 
        if(i == (rows -1)):
            roots[i] = (b[i]) / a[i,i]
        else:
            summ = int(sum(roots * a[i]))
            roots[i] = (b[i] - summ) / a[i,i]
            summ=0
    print('Matrix:')
    print(A)
    print('\nRoots:')
    print(roots)

In [316]:
gauss_solver1(A)

Matrix:
[[ 2  8  2 14]
 [ 0  2 -2  6]
 [ 0  0 -9 18]]

Roots:
[ 5.  1. -2.]


In [317]:
gauss_solver2(A)

Matrix:
[[ 2  8  2 14]
 [ 0  2 -2  6]
 [ 0  0 -9 18]]

Roots:
[ 5.  1. -2.]


In [318]:
A

array([[ 2,  8,  2, 14],
       [ 1,  6, -1, 13],
       [ 2, -1,  2,  5]])